// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1617193875);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 933);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "c437468e-4036-487a-b03f-7ec770b88c2e");
user_pref("calendar.registry.c437468e-4036-487a-b03f-7ec770b88c2e.calendar-main-in-composite", true);
user_pref("calendar.registry.c437468e-4036-487a-b03f-7ec770b88c2e.disabled", true);
user_pref("calendar.registry.c437468e-4036-487a-b03f-7ec770b88c2e.name", "Home");
user_pref("calendar.registry.c437468e-4036-487a-b03f-7ec770b88c2e.type", "storage");
user_pref("calendar.registry.c437468e-4036-487a-b03f-7ec770b88c2e.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Johannesburg");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1617193871763");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.7.1");
user_pref("extensions.lastPlatformVersion", "78.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"472abbb2-6e30-4ec6-a7e7-d1f61d196d39\",\"default-theme@mozilla.org\":\"8dcd36f5-68fb-4830-a6ff-8350b569eaba\",\"google@search.mozilla.org\":\"81d116a0-6258-43c7-9f94-663a924eb481\",\"amazondotcom@search.mozilla.org\":\"85ecd8b9-e41a-4629-9eaf-4026016cc390\",\"bing@search.mozilla.org\":\"7b5f7031-dc17-41af-8b4f-165afad67e9b\",\"ddg@search.mozilla.org\":\"6e7e0c3d-ba1a-4ef2-90c5-61baa4607cd6\",\"wikipedia@search.mozilla.org\":\"f682dd35-98bb-41fc-a90b-db697f662a05\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "0ad98951-7f3e-4b0f-9f98-4522d710913");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 98182);
user_pref("security.sandbox.plugin.tempDirSuffix", "7fc3e1a6-b504-408c-9d16-74fc168d0251");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "f3d41693-6c6e-445e-9045-e849d174c333");
user_pref("toolkit.telemetry.previousBuildID", "20210203182138");
